# pyproject.toml
[project]
name = "neutral_atom_image_analysis"
dynamic = ["description", "readme", "keywords", "classifiers", "authors", "requires-python"]
version = "0.0.1"
dependencies = []
[build-system]
requires = ["setuptools >= 42.0.0", "numpy"]
build-backend = "setuptools.build_meta"
[tool.setuptools.package-data]
hipars = ["*.so", "*.dll","*.pyd"]
